name: Keep TG Awake

on:
  schedule:
     - cron: '15 */9 * * *'
  workflow_dispatch:

jobs:
  ping_render_service:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Render Service
        run: |
         curl -s -o /dev/null "https://tg-employee-bot.onrender.com/health"

