name: Keep TG Awake

on:
  schedule:
     - cron: '15 */9 * * *'
  workflow_dispatch:

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to Render app
        run: |
          curl -I -L https://tg-employee-bot.onrender.com

